#!/bin/bash
SCRIPTDIR=$(dirname "${BASH_SOURCE[0]}")
COMMONDIR=$(realpath "$SCRIPTDIR/scripts/common")
CURRENTDIR=$(pwd)
project=$CURRENTDIR
source $COMMONDIR/general.sh
source $COMMONDIR/project.sh
source $COMMONDIR/setup_ip.sh
source $COMMONDIR/traverse.sh
source $COMMONDIR/add_host.sh
source $COMMONDIR/network.sh
source $COMMONDIR/nmap.sh
source $COMMONDIR/searchsploit.sh
source $COMMONDIR/gobuster.sh
source $COMMONDIR/xfreerdp.sh
source $COMMONDIR/ssh_utils.sh
source $COMMONDIR/http_server.sh
source $COMMONDIR/reverse_shell.sh
source $COMMONDIR/responder.sh
source $COMMONDIR/windows_escalate.sh
source $COMMONDIR/linux_escalate.sh
source $COMMONDIR/exploits.sh
source $COMMONDIR/pivot.sh
source $COMMONDIR/ad_tools.sh
source $COMMONDIR/ad_enumeration.sh
source $COMMONDIR/offsec.sh
source $COMMONDIR/password_cracking.sh
source $COMMONDIR/wpscan.sh
source $COMMONDIR/windows_enumeration.sh
source $COMMONDIR/sqli.sh
source $COMMONDIR/web_utils.sh
source $COMMONDIR/client_side_attacks.sh
source $COMMONDIR/linux_enumeration.sh
source $COMMONDIR/snmp.sh
source $COMMONDIR/metasploit.sh
source $COMMONDIR/smtp.sh
source $COMMONDIR/smb.sh
source $COMMONDIR/ftp.sh
source $COMMONDIR/kerbrute.sh
source $COMMONDIR/ldap.sh
source $COMMONDIR/joomla.sh
source $COMMONDIR/hydra.sh
source $COMMONDIR/rmi.sh
